from typing import Protocol, runtime_checkable


@runtime_checkable
class DocumentStoragePort(Protocol):
    async def store(self, filename: str, content: bytes) -> str: ...
    async def retrieve(self, path: str) -> bytes: ...
    async def delete(self, path: str) -> None: ...
